/*
 * flop-strategy
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package flsopenapi

type BoardSuitsType string

// List of BoardSuitsType
const (
	BOARD_SUITS_TYPE_MONO_TONE BoardSuitsType = "BoardSuitsTypeMonoTone"
	BOARD_SUITS_TYPE_TWO_TONE  BoardSuitsType = "BoardSuitsTypeTwoTone"
	BOARD_SUITS_TYPE_RAINBOW   BoardSuitsType = "BoardSuitsTypeRainbow"
)
