/* tslint:disable */
/* eslint-disable */
/**
 * flop-strategy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BoardSuitsType {
    BoardSuitsTypeMonoTone = 'BoardSuitsTypeMonoTone',
    BoardSuitsTypeTwoTone = 'BoardSuitsTypeTwoTone',
    BoardSuitsTypeRainbow = 'BoardSuitsTypeRainbow'
}

export function BoardSuitsTypeFromJSON(json: any): BoardSuitsType {
    return BoardSuitsTypeFromJSONTyped(json, false);
}

export function BoardSuitsTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardSuitsType {
    return json as BoardSuitsType;
}

export function BoardSuitsTypeToJSON(value?: BoardSuitsType | null): any {
    return value as any;
}

