/* tslint:disable */
/* eslint-disable */
/**
 * flop-strategy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum BoardConnectType {
    BoardConnectTypeDisconnect = 'BoardConnectTypeDisconnect',
    BoardConnectTypeConnected = 'BoardConnectTypeConnected'
}

export function BoardConnectTypeFromJSON(json: any): BoardConnectType {
    return BoardConnectTypeFromJSONTyped(json, false);
}

export function BoardConnectTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BoardConnectType {
    return json as BoardConnectType;
}

export function BoardConnectTypeToJSON(value?: BoardConnectType | null): any {
    return value as any;
}

