/* tslint:disable */
/* eslint-disable */
/**
 * flop-strategy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum HighCard {
    HighCardA = 'HighCardA',
    HighCardK = 'HighCardK',
    HighCardQ = 'HighCardQ',
    HighCardJ = 'HighCardJ',
    HighCardT = 'HighCardT',
    HighCard8To9 = 'HighCard_8_To_9',
    HighCard5To7 = 'HighCard_5_To_7',
    HighCard2To4 = 'HighCard_2_To_4'
}

export function HighCardFromJSON(json: any): HighCard {
    return HighCardFromJSONTyped(json, false);
}

export function HighCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): HighCard {
    return json as HighCard;
}

export function HighCardToJSON(value?: HighCard | null): any {
    return value as any;
}

