/* tslint:disable */
/* eslint-disable */
/**
 * flop-strategy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * You can spot the error cause in detail by checking this code.
     * 
     * * `INVALID_ARGUMENT` - The arguments is invalid
     * @type {string}
     * @memberof ModelError
     */
    code?: ModelErrorCodeEnum;
    /**
     * A developer-facing error message.
     * @type {string}
     * @memberof ModelError
     */
    message?: string;
    /**
     * A user-friendly error message.
     * @type {string}
     * @memberof ModelError
     */
    localizedMessage?: string;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'localizedMessage': !exists(json, 'localized_message') ? undefined : json['localized_message'],
    };
}

export function ModelErrorToJSON(value?: ModelError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'localized_message': value.localizedMessage,
    };
}

/**
* @export
* @enum {string}
*/
export enum ModelErrorCodeEnum {
    CodeInvalidArgument = 'CodeInvalidArgument'
}


