/* tslint:disable */
/* eslint-disable */
/**
 * flop-strategy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PlayerPosition {
    PlayerPositionSB = 'PlayerPositionSB',
    PlayerPositionBB = 'PlayerPositionBB',
    PlayerPositionUTG = 'PlayerPositionUTG',
    PlayerPositionHJ = 'PlayerPositionHJ',
    PlayerPositionCO = 'PlayerPositionCO',
    PlayerPositionBTN = 'PlayerPositionBTN'
}

export function PlayerPositionFromJSON(json: any): PlayerPosition {
    return PlayerPositionFromJSONTyped(json, false);
}

export function PlayerPositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerPosition {
    return json as PlayerPosition;
}

export function PlayerPositionToJSON(value?: PlayerPosition | null): any {
    return value as any;
}

