/* tslint:disable */
/* eslint-disable */
/**
 * flop-strategy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PlayerPositionType {
    PlayerPositionTypeInPosition = 'PlayerPositionTypeInPosition',
    PlayerPositionTypeOutOfPosition = 'PlayerPositionTypeOutOfPosition'
}

export function PlayerPositionTypeFromJSON(json: any): PlayerPositionType {
    return PlayerPositionTypeFromJSONTyped(json, false);
}

export function PlayerPositionTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlayerPositionType {
    return json as PlayerPositionType;
}

export function PlayerPositionTypeToJSON(value?: PlayerPositionType | null): any {
    return value as any;
}

