/*
 * flop-strategy
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type HighCard string

// List of HighCard
const (
	HIGH_CARD_A      HighCard = "HighCardA"
	HIGH_CARD_K      HighCard = "HighCardK"
	HIGH_CARD_Q      HighCard = "HighCardQ"
	HIGH_CARD_J      HighCard = "HighCardJ"
	HIGH_CARD_T      HighCard = "HighCardT"
	HIGH_CARD_8_TO_9 HighCard = "HighCard_8_To_9"
	HIGH_CARD_5_TO_7 HighCard = "HighCard_5_To_7"
	HIGH_CARD_2_TO_4 HighCard = "HighCard_2_To_4"
)
