/*
 * flop-strategy
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type BoardPairedType string

// List of BoardPairedType
const (
	BOARD_PAIRED_TYPE_UNPAIRED BoardPairedType = "BoardPairedTypeUnpaired"
	BOARD_PAIRED_TYPE_PAIRED   BoardPairedType = "BoardPairedTypePaired"
	BOARD_PAIRED_TYPE_TRIPS    BoardPairedType = "BoardPairedTypeTrips"
)
