/*
 * flop-strategy
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PlayerPositionType string

// List of PlayerPositionType
const (
	PLAYER_POSITION_TYPE_IN_POSITION     PlayerPositionType = "PlayerPositionTypeInPosition"
	PLAYER_POSITION_TYPE_OUT_OF_POSITION PlayerPositionType = "PlayerPositionTypeOutOfPosition"
)
