/*
 * flop-strategy
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type PotType string

// List of PotType
const (
	POT_TYPE_SRP   PotType = "PotTypeSRP"
	POT_TYPE_3_BET PotType = "PotType_3_Bet"
	POT_TYPE_4_BET PotType = "PotType_4_Bet"
)
