/*
 * flop-strategy
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type PlayerPosition string

// List of PlayerPosition
const (
	PLAYER_POSITION_SB  PlayerPosition = "PlayerPositionSB"
	PLAYER_POSITION_BB  PlayerPosition = "PlayerPositionBB"
	PLAYER_POSITION_UTG PlayerPosition = "PlayerPositionUTG"
	PLAYER_POSITION_HJ  PlayerPosition = "PlayerPositionHJ"
	PLAYER_POSITION_CO  PlayerPosition = "PlayerPositionCO"
	PLAYER_POSITION_BTN PlayerPosition = "PlayerPositionBTN"
)
