/*
 * flop-strategy
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type BoardPairType string

// List of BoardPairType
const (
	BOARD_PAIR_TYPE_UNPAIRED BoardPairType = "BoardPairTypeUnpaired"
	BOARD_PAIR_TYPE_PAIRED   BoardPairType = "BoardPairTypePaired"
	BOARD_PAIR_TYPE_TRIPS    BoardPairType = "BoardPairTypeTrips"
)
