/*
 * flop-strategy
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type GetFlopSituationsParameterResponseImages struct {
	Url string `json:"url"`

	Name string `json:"name"`

	Description string `json:"description"`
}
