/*
 * flop-strategy
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type GetFlopSituationsParameterResponse struct {
	IpBetFreq float32 `json:"ip_bet_freq"`

	OopBetFreq float32 `json:"oop_bet_freq"`

	IpCheckFreq float32 `json:"ip_check_freq"`

	OopCheckFreq float32 `json:"oop_check_freq"`

	Ip33BetFreq float32 `json:"ip_33_bet_freq"`

	Oop33BetFreq float32 `json:"oop_33_bet_freq"`

	Ip67BetFreq float32 `json:"ip_67_bet_freq"`

	Oop67BetFreq float32 `json:"oop_67_bet_freq"`

	IpEquity float32 `json:"ip_equity"`

	OopEquity float32 `json:"oop_equity"`

	HeroPositionType PlayerPositionType `json:"hero_position_type"`

	ImageUrl string `json:"image_url,omitempty"`

	Description string `json:"description,omitempty"`
}
